name: CI Flask App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del código
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Configurar versión de Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13.2"   # Cambia según tu proyecto

      # 3. Instalar dependencias
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # 4. Linter 
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      # 5. Tests 
      - name: Run tests
        run: |
          pip install pytest
          pytest -v || echo "No tests found"

      # 6. Correr la app 
      - name: Run Flask app
        run: |
          nohup python app.py &
          sleep 5
          curl -f http://127.0.0.1:5000 || (echo "App did not start" && exit 1)
